Numpy / SciPy

파이썬의 단점
- 속도가 엄청나게 느리다

넘파이의 이유
- 속도가 빠르고 쉽다
- c로 만들어 졌고 벡터화된 데이터구조를 사용하기때문에 빠르다.(stride 개념)

여기서 벡터화란?
- for를 쓰지않는 네가지방법(이터레이터 제너레이터, 컴프리헨션, 재귀, 맵 필터 리듀스)와 연관이 있음 for문은 효율성이 상당히 떨어지기때문에 잘안씀



In [2]:
import numpy as np

파이썬 공식 라이브러리에 array가 있는데 여기서 array라고 하면 일반적으로 homogenous 한 것을 일컫는다.

homogenous 한 타입의 장점은 다음 데이터 타입이 뭐가올지 체크할 필요가 없다.

파이썬에서 numpy array 압도적으로 많이쓴다. 파이썬공식 array는 안쓰인다고 보면된다

> ---

스칼라, 0차원 arrry

In [3]:
a = np.array(1)

In [4]:
a

array(1)

1차원 벡터, 튜플로 입력해도 mutable로 바뀜

In [5]:
a = np.array([1,2])

In [6]:
a

array([1, 2])

2차원 matrix

In [8]:
a = np.array([[1,2],[3,4]])

In [9]:
a

array([[1, 2],
       [3, 4]])

3차원 tensor

In [10]:
a = np.array([[[1,2],[3,4]],[[1,2],[3,4]]])

In [11]:
a

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])

#### cf) 인스턴스화 하는 세가지 방법

1. 클래스를 이용한 인스턴스화
2. 리터럴 방식
3. factory method 방식

In [13]:
a.ndim #차원 확인하는 attribute

3

In [14]:
len(a) # 마찬가지

2

In [17]:
a.shape # 행 , 열 , size 확인

(2, 2, 2)

In [18]:
a.flags #저장방식이 c이냐 fortran 이냐 등 정보를 알려주는 것

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [19]:
a.size ##size는 원소의 개수

8

In [20]:
a.dtype ##어떤 데이터타입을 가지고있는지!

dtype('int32')

단적인 예시를 들어보자 파이썬에서 지원하는 일반적인 리스트와 넘파이 어레이의 처리방식을 비교한다

> 리스트 경우

In [21]:
x = [1,2,3,4]
y = [2,3,4,5]

[a+b for a,b in zip(x,y)]

[3, 5, 7, 9]

In [22]:
x+y ##리스트의 덧셈은 extend 개념으로 들어가게된다

[1, 2, 3, 4, 2, 3, 4, 5]

> 넘파이의 경우

In [25]:
a = np.array([[1,2],[3,4]])
b = np.array([[1,2],[3,4]])
a+b ##간단한 연산이 가능

array([[2, 4],
       [6, 8]])

In [27]:
a*b ##elementwise multiply

array([[ 1,  4],
       [ 9, 16]])

In [28]:
a.T

array([[1, 3],
       [2, 4]])

In [34]:
a.strides

(8, 4)

strides 개념
- 최대공약수로 나누면 2, 2개가 한행으로 가진다
- 2행 2열 실제는 한개지만 strdie를 이용하면 확확 바꿀수 있따

In [35]:
a

array([[1, 2],
       [3, 4]])

This array is stored in memory as 40 bytes, one after the other (known as a contiguous block of memory). The strides of an array tell us how many bytes we have to skip in memory to move to the next position along a certain axis. For example, we have to skip 4 bytes (1 value) to move to the next column, but 20 bytes (5 values) to get to the same position in the next row. As such, the strides for the array x will be (20, 4).

#### cf) _ 정리

파이썬 우리 심심하면 _ 가 나왔잖아

1. 앞에 언더바 한개 붙을때는 뭐 쓴다고 했어 관례상 private 예외) from * 했을때 _ 붙은애 import 된다 안된다 

2. 앞 뒤로 두개 붙였을때 magic method or special method

3. 관례상 필요없는 변수 이름 일 때,,  맨 마지막 결과를 출력 시키곤함

4. 언더바가 하나 붙고 _(a) 다국어 처리할때 

5. 이름뒤에 _붙어 있을때는 관례상 뭐할때 쓰냐면 python keyword 하고 똑같을때 이름 충돌을 피하기 위해서 쓴다.

In [36]:
a = np.arange(30).reshape(10,3) ##10행 3열
## reshpae을 쓰면 구조를 정해줄수 있음

In [37]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

axis 개념은 뭐냐면

행 끼리 계산 하는건 axis = 0 열끼리 계산 하는건 axis = 1 

stride가 있으면 이거 계산 하는게 빠르고 쉽다 왜 ? 값찾는게 쉬우니까...



In [38]:
np.mean(a, axis=1), np.mean(a, axis=0)

(array([ 1.,  4.,  7., 10., 13., 16., 19., 22., 25., 28.]),
 array([13.5, 14.5, 15.5]))

#### cf) copy 개념

> shallow copy
- shallow copy는 말그대로 얕은 복사 슬라이싱이든 메소드든 써도 새로운 id가 부여되어 서로 영향 받지 않음 .copy와 같음

> deep copy
- 깊은 복사는 내부에 객체들까지 모두 새롭게 copy 되는 것. .deepcopy 메소드로 이용가능

이거 개념이 굉장히 헷갈릴 수 있음 여기 참고하자

https://wikidocs.net/16038

* 그런데 numpy 에서는 view가 shallow copy method 이고 copy가 deep copy method가 된다

#### cf) mutable

1. 자기자신은 바뀌지만 return 값이 none

2. return 값이 있지만 안바뀌는경우

3. return 값도 있고 바뀌는 pop같은 애들

In [46]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
a.reshape(2,5) 

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [49]:
a ## reshape 했는데도 값이 바뀌지는 않음

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
a = a.reshape(2,5)

In [56]:
np.sum(a, axis=0), np.sum(a, axis=1), np.sum(a) ##축에 따른 sum

(array([ 5,  7,  9, 11, 13]), array([10, 35]), 45)

In [57]:
a.sum()

45

np.zeros 는 shape만 정해주면 모든 값을 0으로 채워줌

In [67]:
a = np.zeros((3,4))

In [68]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

np.ones_like(a) a의 shpae에 모두 1을 넣는다.

In [69]:
np.ones_like(a)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [60]:
a = np.ones((3,4))

In [61]:
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

np.eye(4) 단위행렬

In [72]:
a = np.eye(4)

In [73]:
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

마찬가지 단위행렬

In [74]:
a = np.identity(3)

In [75]:
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

대각행렬

In [76]:
a = np.diag((3,4))

In [77]:
a

array([[3, 0],
       [0, 4]])

np.full (3,2) shape에 6으로 채우겠다

In [78]:
a = np.full((3,2),6)

In [79]:
a

array([[6, 6],
       [6, 6],
       [6, 6]])

In [80]:
a = np.linspace(0,99)

In [81]:
a

array([ 0.        ,  2.02040816,  4.04081633,  6.06122449,  8.08163265,
       10.10204082, 12.12244898, 14.14285714, 16.16326531, 18.18367347,
       20.20408163, 22.2244898 , 24.24489796, 26.26530612, 28.28571429,
       30.30612245, 32.32653061, 34.34693878, 36.36734694, 38.3877551 ,
       40.40816327, 42.42857143, 44.44897959, 46.46938776, 48.48979592,
       50.51020408, 52.53061224, 54.55102041, 56.57142857, 58.59183673,
       60.6122449 , 62.63265306, 64.65306122, 66.67346939, 68.69387755,
       70.71428571, 72.73469388, 74.75510204, 76.7755102 , 78.79591837,
       80.81632653, 82.83673469, 84.85714286, 86.87755102, 88.89795918,
       90.91836735, 92.93877551, 94.95918367, 96.97959184, 99.        ])

In [82]:
a = np.logspace(1,100)

In [83]:
a

array([1.00000000e+001, 1.04811313e+003, 1.09854114e+005, 1.15139540e+007,
       1.20679264e+009, 1.26485522e+011, 1.32571137e+013, 1.38949549e+015,
       1.45634848e+017, 1.52641797e+019, 1.59985872e+021, 1.67683294e+023,
       1.75751062e+025, 1.84206997e+027, 1.93069773e+029, 2.02358965e+031,
       2.12095089e+033, 2.22299648e+035, 2.32995181e+037, 2.44205309e+039,
       2.55954792e+041, 2.68269580e+043, 2.81176870e+045, 2.94705170e+047,
       3.08884360e+049, 3.23745754e+051, 3.39322177e+053, 3.55648031e+055,
       3.72759372e+057, 3.90693994e+059, 4.09491506e+061, 4.29193426e+063,
       4.49843267e+065, 4.71486636e+067, 4.94171336e+069, 5.17947468e+071,
       5.42867544e+073, 5.68986603e+075, 5.96362332e+077, 6.25055193e+079,
       6.55128557e+081, 6.86648845e+083, 7.19685673e+085, 7.54312006e+087,
       7.90604321e+089, 8.28642773e+091, 8.68511374e+093, 9.10298178e+095,
       9.54095476e+097, 1.00000000e+100])

In [84]:
a = np.empty((4,2)) ##쓰레기값

In [85]:
a

array([[0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 5.23709585e-321],
       [1.02360459e-306, 8.34445561e-308]])

### array에서 특정 값 뽑아내기

In [86]:
a = np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [88]:
a[1][3] ##일반적인 인덱싱

8

In [90]:
a[1,3] ##넘파이에서 이런 고급적인 인덱싱을 지원해줌 

8

In [91]:
a[:,3] ## 4열 뽑아낸거

array([3, 8])

In [92]:
a = np.arange(27).reshape(3,3,3)

3차원

In [93]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [94]:
a[:,:,1]

array([[ 1,  4,  7],
       [10, 13, 16],
       [19, 22, 25]])

In [95]:
a[1,...] ##...은 전부다라는 의미 잘 쓰지는 않음.

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [96]:
a[1,:]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [97]:
a = np.array([(0,1,2,3,4,5),(10,11,12,13,14,15),(20,21,22,23,24,25),(30,31,32,33,34,35),(40,41,42,43,44,45),(50,51,52,53,54,55)])

In [98]:
a[0,3:5]

array([3, 4])

In [99]:
a[:,2]

array([ 2, 12, 22, 32, 42, 52])

In [100]:
a[4:6,4:6]

array([[44, 45],
       [54, 55]])

In [101]:
a[0::2,::2][1:3,]

array([[20, 22, 24],
       [40, 42, 44]])

#### 마스킹 기법

True 인것만 뽑아내겠다

In [102]:
a = np.arange(10)

In [103]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
a[a>3] ##조건가능

array([4, 5, 6, 7, 8, 9])

In [105]:
a[[True,False,True,True,True,True,True,True,True,True]]

array([0, 2, 3, 4, 5, 6, 7, 8, 9])

#### fancy indexing

대괄호 두개로 fancy하게 indexing하겠다

In [106]:
a[[1,2]]

array([1, 2])

In [108]:
a[[-1,-2 ]]  ##뒤에서부터 인덱스

array([9, 8])

인덱싱 예제

In [109]:
a = np.arange(25).reshape(5,5)

In [110]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [111]:
a[0]

array([0, 1, 2, 3, 4])

In [112]:
a[1,3:5]

array([8, 9])

In [113]:
a[:,4]

array([ 4,  9, 14, 19, 24])

In [114]:
a[-2:, -2:]

array([[18, 19],
       [23, 24]])

In [115]:
a[2::2, ::2]

array([[10, 12, 14],
       [20, 22, 24]])

In [116]:
a[[0,1]]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [117]:
a[[1,2,4],[2,3,4]]

array([ 7, 13, 24])

In [118]:
a[3:, [0,1,3]]

array([[15, 16, 18],
       [20, 21, 23]])

#### broaad casting 
넘파이는 크기가 안맞아도 간단한것 정도는 맞춰준다
리스트는 덧셈이 안되쥬?
근데 복잡하면 안해줌

In [120]:
3 + np.arange(10) 

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [121]:
np.array([1,2]) + np.arange(10) ## broadcasting error

ValueError: operands could not be broadcast together with shapes (2,) (10,) 

### ufunc
#### u : unversial

In [122]:
np.abs([-1,1,2]) ##놀랍쥬?

array([1, 1, 2])

In [123]:
np.info(np.ceil) ##넘파이에서 설명 자세하게 보는방법.

ceil(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Return the ceiling of the input, element-wise.

The ceil of the scalar `x` is the smallest integer `i`, such that
`i >= x`.  It is often denoted as :math:`\lceil x \rceil`.

Parameters
----------
x : array_like
    Input data.
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
y : ndarray or scalar
    The ceilin

In [124]:
np.ceil(2.9)

3.0

In [125]:
np.floor(2.9)

2.0

In [126]:
np.round(2.51)

3.0

In [127]:
np.round([2.1,3.1,4.7,5.8])

array([2., 3., 5., 6.])

In [129]:
from scipy.special import factorial

In [130]:
factorial([3,4,5])

array([  6.,  24., 120.])

In [131]:
np.info(factorial) ##scipy 에 있는건데 np.info가 먹힌다 즉 scipy 가 numpy로 부터 만들어짐

 factorial(n, exact=False)

The factorial of a number or array of numbers.

The factorial of non-negative integer `n` is the product of all
positive integers less than or equal to `n`::

    n! = n * (n - 1) * (n - 2) * ... * 1

Parameters
----------
n : int or array_like of ints
    Input values.  If ``n < 0``, the return value is 0.
exact : bool, optional
    If True, calculate the answer exactly using long integer arithmetic.
    If False, result is approximated in floating point rapidly using the
    `gamma` function.
    Default is False.

Returns
-------
nf : float or int or ndarray
    Factorial of `n`, as integer or float depending on `exact`.

Notes
-----
For arrays with ``exact=True``, the factorial is computed only once, for
the largest input, with each other result computed in the process.
The output dtype is increased to ``int64`` or ``object`` if necessary.

With ``exact=False`` the factorial is approximated using the gamma
function:

.. math:: n! = \Gamma(n+1)

Examples


In [132]:
b =  np.arange(5,10)

In [133]:
np.where(b>5, 0, 1) ##5보다크면 0으로 아니면 1로 바꿔라 이거 마스킹에 쓰이는거 아닌가!!! 
## 조건을 만족하는 인덱스.!!!

array([1, 0, 0, 0, 0])

In [134]:
np.where(b>5)

(array([1, 2, 3, 4], dtype=int64),)

In [135]:
b[np.where(b>5)]

array([6, 7, 8, 9])

In [136]:
np.argmax(b) ##가장 큰 인덱스

4

In [137]:
np.argmin(b) ##가장 작은 인덱스

0

> A * B                       
array([[2, 0],
       [0, 4]])               # elementwise product 원소곱
       
> A @ B                       
array([[5, 4],
       [3, 4]])               # matrix product 행렬곱
       
> A.dot(B)                    
array([[5, 4],
       [3, 4]])               # another matrix product 내적