# Numpy

### Numpy array 생성 및 변경

In [1]:
import numpy as np

np.array

In [9]:
array1 = np.array([1,2,3])

print('array1 type:', type(array1))

print('array1 형태:', array1.shape)

array1 type: <class 'numpy.ndarray'>
array1 형태: (3,)


ndarray.shape

In [5]:
print('array1 형태:', array1.shape)

array1 형태: (3,)


In [10]:
array2 = np.array([[1,2,3],
                    [2,3,4]])

print('array2 type:', type(array2))

print('array2 형태:', array2.shape)

array2 type: <class 'numpy.ndarray'>
array2 형태: (2, 3)


In [11]:
array3 = np.array([[1,2,3]])

print('array3 type:', type(array3))

print('array3 형태:', array3.shape)

array3 type: <class 'numpy.ndarray'>
array3 형태: (1, 3)


ndarray.ndim

In [15]:
print('array1:{:0}차원,array2:{:1}차원,array3:{:2}차원,'.format(array1.ndim, array2.ndim, array3.ndim))

array1:1차원,array2:2차원,array3: 2차원,


np.arange

In [16]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


np.zero

In [18]:
zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


np.ones

In [19]:
one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


np.reshape

In [20]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n', array2)

array3 = array1.reshape(5,2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


아래와같이 10개의 데이터를 4x3행렬로 만들려고하면 `ValueError`

In [21]:
array1.reshape(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

실제로는 reshape에서 -1을 굉장히 많이쓴다

In [23]:
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1,5)
print('array2 shape:', array2.shape)
array3 = array1.reshape(5,-1)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


차원을 줄일때 reshape(-1,1)을 유용하게 사용할 수 있다.

In [25]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist())

array5 = array3d.reshape(-1,1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

array6 = array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)


array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


### Numpy array indexing

1. 특정한 데이터만 추출
2. 슬라이싱
3. 팬시 인덱싱
4. 불린 인덱싱

#### 1. 특정한 데이터만 추출

In [27]:
array1 = np.arange(start=1, stop=10)
print('array1:', array1)

array1: [1 2 3 4 5 6 7 8 9]


In [28]:
value = array1[2]
print('value:', value)
print(type(value))

value: 3
<class 'numpy.int32'>


In [29]:
print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두 번째 값:', array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8


아래와 같이 단일 값 추출로 데이터 수정이 가능하다.

In [31]:
array1[0] = 9
array1[8] = 0
print('array1 :', array1)

array1 : [9 2 3 4 5 6 7 8 0]


다차원일 경우에도 인덱싱을 해보자.

In [32]:
array1d = np.arange(start=1, stop = 10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:', array2d[0,0])
print('(row=0, col=1) index 가리키는 값:', array2d[0,1])
print('(row=1, col=0) index 가리키는 값:', array2d[1,0])
print('(row=1, col=1) index 가리키는 값:', array2d[1,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=1, col=1) index 가리키는 값: 5


#### 2. 슬라이싱

In [33]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [34]:
array1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
print(array1[:3])
print(array1[3:])
print(array1[:])

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


2차원 슬라이싱

In [37]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n', array2d)

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [38]:
print(array2d[0:2, 0:2])
print(array2d[1:3, 0:3])
print(array2d[1:3, :])
print(array2d[:, :])
print(array2d[:2, 1:])
print(array2d[:2, 0])

[[1 2]
 [4 5]]
[[4 5 6]
 [7 8 9]]
[[4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]]
[1 4]


2차원 슬라이싱에서의 생략, axis = 0 기준으로 즉, 로우를 반환

In [40]:
print(array2d[0])

print(array2d[1])

[1 2 3]
[4 5 6]


#### 3. 팬시 인덱싱

In [41]:
array1d = np.arange(start=1, stop = 10)
array2d = array1d.reshape(3,3)

In [44]:
array2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
array3 = array2d[[0,1],2]
print('array2d[[0,1],3] =>', array3.tolist())

array4 = array2d[[0,1], 0:2]
print('array2d[[0,1], 0:2] =>', array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]] =>', array5.tolist())

array2d[[0,1],3] => [3, 6]
array2d[[0,1], 0:2] => [[1, 2], [4, 5]]
array2d[[0,1]] => [[1, 2, 3], [4, 5, 6]]


#### 4.불린 인덱싱

In [48]:
array1d = np.arange(start=1, stop=10)
array3 = array1d[array1d>5]
print('불린 인덱싱 결과 값 :', array3)

불린 인덱싱 결과 값 : [6 7 8 9]


### 행렬의 정렬

np.sort() : 원 행렬은 그대로 유지한 채 원 해렬의 정렬된 행렬을 반환  
ndaraay.sort() : 원 행렬 자체를 정렬한 형태로 변환하며 반환 값은 None

In [52]:
org_array = np.array([3,1,9,5])
print('원본 행렬;', org_array)

sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬', org_array)

원본 행렬; [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬 [3 1 9 5]


In [53]:
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort() 호출 후 원본 행렬', org_array)

org_array.sort() 호출 후 반환된 행렬: None
org_array.sort() 호출 후 원본 행렬 [1 3 5 9]


내림차순으로 정렬하기 위해서는 [::-1] 사용

In [55]:
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬', sort_array1_desc)

내림차순으로 정렬 [9 5 3 1]


2차원에서의 정렬

In [56]:
array2d = np.array([[8,12],
                   [7,1 ]])

In [57]:
sort_array2d_axis0 = np.sort(array2d, axis = 0)
print('로우 방향으로 정렬 : \n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis = 1)
print('칼럼 방향으로 정렬 : \n', sort_array2d_axis1)

로우 방향으로 정렬 : 
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬 : 
 [[ 8 12]
 [ 1  7]]


정렬된 행렬의 인덱스를 반환하기 np.argsort()

In [59]:
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


### 선형대수 연산

#### 행렬 내적(곱)

In [60]:
A = np.array([[1,2,3],
             [4,5,6]])
B = np.array([[7,8],
             [9,10],
             [11,12]])
dot_product = np.dot(A,B)
print('행렬 내적 결과:\n',  dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


#### 전치 행렬

In [61]:
A = np.array([[1,2],
             [3,4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
